### ISSUE TITLE
希望添加一个选项来关闭log

### ISSUE THREAD

**Issue by lightsummer233** [UISSD/Miller#2]
短短5个小时，就生成了8mb多的log。。
我不好评价，模块是很好用，但是能不能减少log的输出或者提供关闭log的选项。。
![Screenshot_2023-01-06-21-41-22-804_bin mt plus](https://user-images.githubusercontent.com/93428659/211024417-5a10dce1-1759-4c45-b36f-4ab825840298.jpg)
![Screenshot_2023-01-06-21-41-28-221_bin mt plus](https://user-images.githubusercontent.com/93428659/211024433-7d9d0137-835d-4eb8-9e60-f91e31877cef.jpg)
![IMG_20230106_214505](https://user-images.githubusercontent.com/93428659/211024441-d7c1441c-5d80-4d31-b382-53ca069f16ce.jpg)

**Comment by UISSD** [comment]
之后会考虑加开关来动态日志, 目前只能安装不同版本来选择是否输出日志[https://github.com/UISSD/Miller/releases/tag/v1.1.1](url)

**Comment by lightsummer233** [comment]
换版本不是问题。。其实也不用开关。。问题在于上个版本只有一个release版，而且会像描述的那样产日志。。新版不产日志就好了（）
也感谢大佬回复（）
